#ifndef PLATINEDEFINES_H_INCLUDED
#define PLATINEDEFINES_H_INCLUDED

#define PIN_RGB_RED 0
#define PIN_RGB_GREEN 2
#define PIN_RGB_BLUE 3

#define PIN_SEG_A 26
#define PIN_SEG_B 27
#define PIN_SEG_C 28
#define PIN_SEG_D 29

#define PIN_KEYBOARD_1 6
#define PIN_KEYBOARD_2 5
#define PIN_KEYBOARD_3 4
#define PIN_KEYBOARD_4 1
#define PIN_KEYBOARD_5 16
#define PIN_KEYBOARD_6 15
#define PIN_KEYBOARD_7 21
#define PIN_KEYBOARD_8 22

#endif // PLATINEDEFINES_H_INCLUDED
